### PR TITLE
Avoid expiring of root certificate authority

### LINKED ISSUE #1103: Root CA expires after 730 days without a convenient way to renew it
## Clear description of your problem
The generated root CA `LaravelValetCASelfSigned.pem` expires after 730 days, which will result in the error `cURL error 60: SSL certificate problem: unable to get local issuer certificate` when sending a PHP cURL request to a Valet secured domain.

### Option 1

Valet auto-rotates (renews) the root CA automatically and informs the user to recreate a CA bundle for cURL by running `brew reinstall ca-certificates`.

### Option 2

Valet provides a `valet renew` command that creates a new root CA and creates new certs for existing sites, adds them to the Keychain, then executes `brew reinstall ca-certificates` in order to regenerate a CA certificate bundle from the keychain.

## Current behavior
The root CA expires and things break with `cURL error 60: SSL certificate problem: unable to get local issuer certificate`.

There is no convenient way to create a new root CA and child-certificates for existing sites.

The current workaround is to delete the `valet/CA`-folder and re-secure existing sites.

## Steps to Reproduce

1. Install Valet
2. Wait 731 days and run `brew reinstall ca-certificates` (the CA bundle for cURL won't contain the expire Valet Root CA anymore)
3. Make a https request via PHP cURL to a site secured with Valet
4. Get the error `cURL error 60: SSL certificate problem: unable to get local issuer certificate`
5. Spend a lot of hours in order to figure out how certificate validation on macOS with cURL and PHP works 🙃 

### Output of these steps
/

## Possible solution

Valet either auto-rotates the root CA (by checking its age) or provides a command to manually renew the root CA.

I can provide a PR for one of these options, if desired.

## Diagnosis
<details>
    <summary>sw_vers</summary>
    <pre>ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165</pre>
</details>
<details>
    <summary>valet --version</summary>
    <pre>Laravel Valet 2.16.0</pre>
</details>

### PR DESCRIPTION
**Pull request by jaylinski**
### Description

Currently Laravel Valet creates a root certificate authority with the same validity period as normal certificates.

It is correct to limit normal certificates to a maximum of 396 days in order to adhere to certificate baseline-requirements as defined in https://github.com/cabforum/servercert/blob/main/docs/BR.md (2020-09-01).

But the validity of root CAs is not limited, thus it makes sense to create the root CA with a longer validity period. The Lets Encrypt Root CA `ISRG Root X1` has a validity period of 20 years, so that should also be the default period of the Laravel Valet Root CA.

This resolves #1103 without having to implement auto-rotation of expired root CAs. (Because the amount of people that use the same machine and OS for over 20 years is probably zero.)

There is only one downside: existing users won't benefit from this change, because they would have to manually delete the root CA from the keychain in order for Valet to create a new CA. But since I was the first one to complain about this issue, I guess this doesn't matter that much.

### Screenshot

Bildschirmfoto 2021-12-16 um 17 18 32

### CODE REVIEW

File: cli/Valet/Site.php [hunk 1]
```diff
@@ -464,10 +464,13 @@ public function secured()
...
      * @param  string  $siteConf  pregenerated Nginx config file contents
-     * @param  int  $caExpireInDays  The mount of days the self signed certificate is valid.
+     * @param  int  $certificateExpireInDays  The amount of days the self signed certificate is valid.
+     *                                        Certificates SHOULD NOT have a validity period greater than 397 days.
+     * @param  int  $caExpireInYears  The amount of years the certificate authority is valid.
+     * @see https://github.com/cabforum/servercert/blob/main/docs/BR.md
      * @return void
      */
-    public function secure($url, $siteConf = null, $caExpireInDays = 368)
+    public function secure($url, $siteConf = null, $certificateExpireInDays = 396, $caExpireInYears = 20)
```
Comment (jaylinski) [inline cli/Valet/Site.php:473]: I'm not sure why `368` was picked by @icyrizard, according to the baseline-requirements it can be 396 days:

https://github.com/cabforum/servercert/blob/main/docs/BR.md (2020-09-01)

File: cli/Valet/Site.php [hunk 2]
```diff
@@ -477,8 +480,11 @@ public function secure($url, $siteConf = null, $caExpireInDays = 368)
 
         $this->files->ensureDirExists($this->nginxPath(), user());
 
-        $this->createCa($caExpireInDays);
-        $this->createCertificate($url, $caExpireInDays);
+        $caExpireInterval = (new \DateInterval(sprintf('P%dY', $caExpireInYears)));
+        $caExpireInDate = (new \DateTime())->diff((new \DateTime())->add($caExpireInterval));
+
+        $this->createCa($caExpireInDate->format('%a'));
```
Comment (jaylinski) [inline cli/Valet/Site.php:486]: Simpler alternative: `$this->createCa($caExpireInYears * 365)` (but this misses leap years)

Comment (mattstauffer) [reply cli/Valet/Site.php:488]: Good note--love this even if it's bit less simple

File: cli/Valet/Site.php (hunk 1 above)
Comment (mattstauffer) [reply cli/Valet/Site.php:475]: Yah, I checked the original PR: https://github.com/laravel/valet/pull/1154 

And there's no explanation given, so I'm totally fine for moving it to 396. Good catch!

File: cli/Valet/Site.php [hunk 3]
```diff
@@ -477,8 +482,11 @@ public function secure($url, $siteConf = null, $caExpireInDays = 368)
...
```
Comment (mattstauffer) [inline cli/Valet/Site.php:488]: What if we simplify this a bit?

```suggestion
        $caExpireInDate = (new DateTime())->diff(new DateTime("+{$caExpireInYears} years"));
        $this->createCa($caExpireInDate->format('%a'));
```

File: cli/Valet/Site.php [hunk 4]
```diff
@@ -488,7 +496,7 @@ public function secure($url, $siteConf = null, $caExpireInDays = 368)
     /**
      * If CA and root certificates are nonexistent, create them and trust the root cert.
      *
-     * @param  int  $caExpireInDays  The mount of days the self signed certificate is valid.
+     * @param  int  $caExpireInDays  The mount of days the self signed certificate authority is valid.
```
Comment (mattstauffer) [inline cli/Valet/Site.php:499]:
```suggestion
     * @param  int  $caExpireInDays  The number of days the self signed certificate authority is valid.
```

**Review by mattstauffer — CHANGES_REQUESTED** [review]
I just suggested a tiny refactor. Great work here!

File: cli/Valet/Site.php (hunk 3 above)
Comment (jaylinski) [reply cli/Valet/Site.php]: Much better, yes. :+1:

File: cli/Valet/Site.php (hunk 4 above)
Comment (jaylinski) [reply cli/Valet/Site.php]: :+1: Done.

I also corrected this for the function `Site::createCertificate()`.

**Comment by mattstauffer** [comment]
Fantastic. Thank you so much @jaylinski!
