### PR TITLE
Fix subdomains pointing to root path

### LINKED ISSUE #1032: Subdomain is pointing to root domain, even though they have different folders linked.
## Clear description of your problem

I have a root folder called Onlysort, which contains 2 sub-folders: app and homepage. The app is a Laravel installation and the homepage is a jigsaw installation. I have the homepage linked to `Onlysort` and the app linked to `app.onlysort` now, when I visit both urls, it takes me to the homepage link (Onlysort.test)

## Expected behavior

app.onlysort.test to visit the app folder
onlysort.test to visit the homepage folder

## Diagnosis

`<details>
<summary>sw_vers</summary>
<pre>ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.13.19</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "paths": [
        "/Users/nate/.config/valet/Sites"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^2.13"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/nate/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.7 => 2.0.9)
Composer version: 2.0.7
PHP version: 8.0.0
PHP binary path: /usr/local/Cellar/php/8.0.0_1/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.74.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1i
zip extension: OK</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/nate/.composer
illuminate/container v8.25.0 ! v8.26.1 The Illuminate Container package.
illuminate/contracts v8.25.0 ! v8.26.1 The Illuminate Contracts package.
symfony/console      v5.2.2  ! v5.2.3  Eases the creation of beautiful and testable command line interfaces
symfony/process      v5.2.2  ! v5.2.3  Executes commands in sub-processes
symfony/string       v5.2.2  ! v5.2.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/var-dumper   v5.2.2  ! v5.2.3  Provides mechanisms for walking through any arbitrary PHP variable</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x   2 root  wheel    64  1 Jan  2020 .
drwxr-xr-x  87 root  wheel  2784 31 Jan 18:28 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 3.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ebc7cc36a0e029d58fac8cebd1b5ff583b3fd95b
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1a52ade05ee2d88080e532362ef54a721dd5703c
Core tap last commit: 3 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name    Status  User Plist
dnsmasq unknown root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql   started nate /Users/nate/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx   unknown root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php     unknown root /Library/LaunchDaemons/homebrew.mxcl.php.plist
unbound stopped</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.83
mysql 8.0.23
nginx 1.19.6
openssl@1.1 1.1.1i
php 8.0.0_1</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>aom
apr
bdw-gc
cairo
composer
curl
dav1d
dnsmasq
ffmpeg
freetds
gd
glib
guile
harfbuzz
krb5
libffi
libsndfile
libtiff
nettle
nghttp2
node
openjpeg
openldap
php
python@3.9
rav1e
sdl2
webp
x264
x265
zstd</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>homebrew/cask
homebrew/core
homebrew/services</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 8.0.0 (cli) (built: Nov 30 2020 13:51:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/8.0
Loaded Configuration File:         /usr/local/etc/php/8.0/php.ini
Scan for additional .ini files in: /usr/local/etc/php/8.0/conf.d
Additional .ini files parsed:      /usr/local/etc/php/8.0/conf.d/error_log.ini,
/usr/local/etc/php/8.0/conf.d/ext-opcache.ini,
/usr/local/etc/php/8.0/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.19.6</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.74.0
Age => 7
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin20.1.0
SSL Version => (SecureTransport) OpenSSL/1.1.1i
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.35</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/nate/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.19.6 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.19.6 (25 files, 2.2MB) *
  Poured from bottle on 2021-01-24 at 18:13:34
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 36,932 (30 days), 127,237 (90 days), 453,960 (365 days)
install-on-request: 36,865 (30 days), 126,490 (90 days), 445,150 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 8.0.2 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.0.0_1 (500 files, 77.8MB) *
  Poured from bottle on 2020-12-14 at 15:31:49
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, glib, gmp, icu4c, krb5, libffi, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.0/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 57,045 (30 days), 162,457 (90 days), 616,898 (365 days)
install-on-request: 55,869 (30 days), 159,196 (90 days), 594,777 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@1.1: stable 1.1.1i (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1i (8,067 files, 18.5MB)
  Poured from bottle on 2020-12-14 at 15:29:02
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
License: OpenSSL
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Analytics
install: 711,341 (30 days), 2,267,181 (90 days), 8,189,687 (365 days)
install-on-request: 111,538 (30 days), 359,704 (90 days), 1,184,417 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.0.0 (fpm-fcgi) (built: Nov 30 2020 13:52:05)
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/8.0/php-fpm.conf --test</summary>
<pre>[06-Feb-2021 12:25:36] NOTICE: configuration file /usr/local/etc/php/8.0/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 nate  staff   543 31 Jan 19:37 homebrew.mxcl.mysql.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657  6 Feb 12:09 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571  6 Feb 12:09 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   628  6 Feb 12:09 homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22  1 Jan  2020 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search Home
nameserver 192.168.0.1
nameserver fd11:8500:4a2e:0:681:9bff:fe3c:82e0</pre>
</details>`

### PR DESCRIPTION
**Pull request by lpheller**
Closes #1032

This PR reverts the changes from #1018 and fixes the problem with subdomains described in #1032.

The "breaking" change was in [server.php#L144](https://github.com/laravel/valet/blob/master/server.php#L144)
```php
            if (strtolower($file) === $domain) {
                $valetSitePath = $path.'/'.$file;
                break;
            }
```

The `break` statement stopped the execution of the loop too early, as `$domain` is not what we are looking for at this very moment, when using a linked subdomain.

I actually was able to reproduce the problem @mrk-j described in #1018 too and solved this by re-adding his outer break statement, but removing the early breaks. 

So, this should fix both problems described in #1018 and #1032.

### CODE REVIEW

**Comment by drbyte** [comment]
@lpheller thanks for this.
Since it's gone around a few iterations with people saying it didn't work for their scenario, it seems like it's a situation that's begging for some tests in the test suite. 
Do you mind adding some tests for this logic? (I'm aware that the affected file has no test coverage presently.)

**Comment by lpheller** [comment]
Yes, some tests for this would be great and I'd love to help and add to it. But honestly, I'm a little lost right now on how to approach testing the logic in this particular file. I guess I need to dig a little deeper. 🧐

**Comment by cbl** [comment]
Writing tests would require to move logic of the `server.php` into functions which then can be tested. The `server.php` is a risky place at the moment. 😬
Would you accept a restructuring of this file @drbyte ?

**Comment by drbyte** [comment]
`server.php` ... I agree it's a risky place. Not sure I want it refactored significantly. Apart from the few functions it declares, it operates very straightforwardly as simple procedural code.

That said, splitting out this `foreach` section for setting `$valetSitePath` into a function of its own would be simple, since it only needs to return one value.

**Comment by billmn** [comment]
Any update about this?

**Comment by lpheller** [comment]
I'm really sorry, I hadn't managed to get back to this and was then absent for some time. I'll take a look at this again now. 
Turning the foreach into a function as suggested, shouldn't be a problem.

File: server.php [hunk 1]
```diff
@@ -125,33 +125,32 @@ function valet_default_site_path($config)
...
-        closedir($handle);
-        
-        if ($valetSitePath) {
-            break;
-        }
     }
 }
 
+$domain = array_slice(explode('.', $siteName), -1)[0];
+$valetSitePath = get_valet_site_path($valetConfig, $siteName, $domain);
```
Comment (drbyte) [inline server.php:152]: This doesn't match the function signature: `
function get_valet_site_path($valtetConfig, $domain, $siteName)`

File: server.php [hunk 2]
```diff
@@ -125,33 +125,32 @@ function valet_default_site_path($config)
...
-    if ($handle = opendir($path)) {
-        while (false !== ($file = readdir($handle))) {
-            if (! is_dir($path.'/'.$file)) continue;
-            if (in_array($file, ['.', '..', '.DS_Store'])) continue;
-
-            // match dir for lowercase, because Nginx only tells us lowercase names
-            if (strtolower($file) === $siteName) {
-                $valetSitePath = $path.'/'.$file;
-                break;
+function get_valet_site_path($valtetConfig, $domain, $siteName)
```
Comment (drbyte) [inline server.php:128]: `$valtetConfig` seems to bemisspelled, and doesn't match the var in the rest of the function.

Comment (lpheller) [reply server.php]: Oh wow, what a mess, sorry. I guess I rushed it a bit too much there.

File: server.php (hunk 1 above)
Comment (lpheller) [reply server.php:152]: Fixed. I wonder why it still worked for me though.

**Review by drbyte — APPROVED** [review]
This change tests fine for me when recreating the described scenarios, and doesn't break other sites.

@mattstauffer This PR should be marked as closing #1032

**Comment by kirkbushell** [comment]
This is excellent - can't wait to have this fixed :)

**Comment by mattstauffer** [comment]
Sorry for the delay y'all :)

**Comment by mattstauffer** [comment]
Released in 2.15.1 (https://github.com/laravel/valet/releases/tag/v2.15.1)

**Comment by lpheller** [comment]
@mattstauffer sure, will do so!
