### PR TITLE
Fix php errors from #241 (valet tld command)

### LINKED ISSUE #618: Valet breaks if TLD is not set on latest
#241 introduces a bug for those updating from a previous version which breaks Valet until you run `valet tld ...`

image

The configuration should fallback to the previous `domain` setting if `tld` is not set (or migrate it?).

Running `valet tld test` fixed it for me, but also emitted the following errors

```
PHP Notice:  Undefined index: tld in /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php on line 77
PHP Stack trace:
PHP   1. {main}() /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:0

Notice: Undefined index: tld in /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php on line 77

Call Stack:
    0.0053     446888   1. {main}() /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:0

PHP Notice:  Undefined index: tld in /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php on line 67
PHP Stack trace:
PHP   1. {main}() /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:0
PHP   2. Silly\Application->run() /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:282
PHP   3. Silly\Application->doRun() /Users/aaemnnosttv/.composer/vendor/symfony/console/Application.php:148
PHP   4. Silly\Application->doRunCommand() /Users/aaemnnosttv/.composer/vendor/symfony/console/Application.php:248
PHP   5. Silly\Command\Command->run() /Users/aaemnnosttv/.composer/vendor/symfony/console/Application.php:946
PHP   6. Silly\Application->Silly\{closure}() /Users/aaemnnosttv/.composer/vendor/symfony/console/Command/Command.php:249
PHP   7. Invoker\Invoker->call() /Users/aaemnnosttv/.composer/vendor/mnapoli/silly/src/Application.php:85
PHP   8. call_user_func_array:{/Users/aaemnnosttv/.composer/vendor/php-di/invoker/src/Invoker.php:82}() /Users/aaemnnosttv/.composer/vendor/php-di/invoker/src/Invoker.php:82
PHP   9. Silly\Application->{closure:/Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:61-77}() /Users/aaemnnosttv/.composer/vendor/php-di/invoker/src/Invoker.php:82

Notice: Undefined index: tld in /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php on line 67

Call Stack:
    0.0053     446888   1. {main}() /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:0
    0.0290    2713512   2. Silly\Application->run() /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:282
    0.0391    3033280   3. Silly\Application->doRun() /Users/aaemnnosttv/.composer/vendor/symfony/console/Application.php:148
    0.0392    3033280   4. Silly\Application->doRunCommand() /Users/aaemnnosttv/.composer/vendor/symfony/console/Application.php:248
    0.0392    3033280   5. Silly\Command\Command->run() /Users/aaemnnosttv/.composer/vendor/symfony/console/Application.php:946
    0.0396    3038488   6. Silly\Application->Silly\{closure}() /Users/aaemnnosttv/.composer/vendor/symfony/console/Command/Command.php:249
    0.0397    3039664   7. Invoker\Invoker->call() /Users/aaemnnosttv/.composer/vendor/mnapoli/silly/src/Application.php:85
    0.0397    3040232   8. call_user_func_array:{/Users/aaemnnosttv/.composer/vendor/php-di/invoker/src/Invoker.php:82}() /Users/aaemnnosttv/.composer/vendor/php-di/invoker/src/Invoker.php:82
    0.0397    3040624   9. Silly\Application->{closure:/Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:61-77}() /Users/aaemnnosttv/.composer/vendor/php-di/invoker/src/Invoker.php:82
```

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #618

This now forces a migration of the 'domain' key to 'tld' in the config, to make it easier for upgraders from v2.0.0-2.0.12 to newer.

### CODE REVIEW

File: cli/Valet/Configuration.php [hunk 1]
```diff
@@ -115,12 +115,21 @@ function writeBaseConfiguration()
...
+            return;
+        }
+
+        $tld = 'test';
+
+        if (isset($config['domain'])) {
+            $tld = $config['domain'];
         }
+
+        $this->updateKey('tld', $tld);
```
Comment (mattstauffer) [inline cli/Valet/Configuration.php]: Could we do:

```php
$this->updateKey('tld', $config['domain'] ?? 'test');
```

Comment (drbyte) [reply cli/Valet/Configuration.php]: Valet is designed to support PHP 5.6, so can't use null-coalesce, however, can certainly shorten the code down similarly. 

Pushed squashed update.

Comment (mattstauffer) [reply cli/Valet/Configuration.php]: Whoa I totally thought we had moved past. Good catch!
