### PR TITLE
Fix auto-detection amongst multiple ngrok processes

### LINKED ISSUE #145: Valet Share does not copy or show the latest ngrok url, but only the first one
If you use it more than once, it'll open up multiple ngrok instances (which is fine), but it will keep displaying and copying to the clipboard only the first one.

### PR DESCRIPTION
**Pull request by drbyte**
Ngrok Pro plans allow multiple processes, which means you could be serving several sites simultaneously. This PR allows Valet to correctly identify amongst the active ngrok process URLs.

Fixes #145

### CODE REVIEW

File: cli/valet.php [hunk 1]
```diff
@@ -226,8 +226,8 @@
     /**
      * Echo the currently tunneled URL.
      */
-    $app->command('fetch-share-url', function () {
-        output(Ngrok::currentTunnelUrl());
+    $app->command('fetch-share-url [domain]', function ($domain = null) {
+        output(Ngrok::currentTunnelUrl($domain ?: Site::host(getcwd()).'.'.Configuration::read()['tld']));
```
Comment (mattstauffer) [inline cli/valet.php]: Would this struggle if someone's parked it as something else?

Comment (drbyte) [reply cli/valet.php]: If they've linked it to something other than the same as the foldername, then the `Site::host()` function resolves the link and uses that instead.

https://github.com/laravel/valet/blob/52b3b47db8ea0f77dee00af3a6c78a7c810cc597/cli/Valet/Site.php#L62-L77

Comment (mattstauffer) [reply cli/valet.php]: brilliant

**Comment by mattstauffer** [comment]
You are the best
